Nombre_usuario = input("Hola, por favor ingresa tu nombre")
Edad_usuario = int(input("Ingresa tu edad"))
print(Edad_usuario *2)
Entero_1_usuario = int(input("Ingresa un número entero"))
Enteros_2_usuario = int(input("Ingresa otro número entero"))
print(Entero_1_usuario + Enteros_2_usuario)
Decimal_usuario = (float(input("Ingresa un número decimal")))
print(Decimal_usuario / 2)
Año_usuario = int(input("Ingresa tu año de nacimiento"))
Año_actual = 2025
print(Año_actual - Año_usuario)
Precio_usuario = int(input("Ingresa precio del producto"))
Unidades_usuario = int(input("Ingresa unidades del producto"))
Precio_total = (Precio_usuario * Unidades_usuario)
Mesanje = "El precio total es de:"
print(Mesanje), print(Precio_total)
Enteros_3_usuario = int(input("Ingresa un número entero"))
print(Enteros_3_usuario * Enteros_3_usuario)
Numero_1_usuario = int(input("Ingresa un número"))
Numero_2_usuario = int(input("Ingresa otro número"))
Promedio_usuario = (Numero_1_usuario + Numero_2_usuario)/ 2
print(Promedio_usuario)
Nombre_usuario_2 = input("Ingresa tu nombre completo")
Edad_usuario_2 = int(input("Ingresa tu edad"))
print(f"Hola, {Nombre_usuario_2}. Tienes {Edad_usuario_2} años.")